INSERT INTO ABVVTFXA.FZZ
(LIDNUMMER_INTERNAL_KEY, GEBRUIKER_WIJZIGING, DATUM_WIJZIGING, DATUM_OVERLIJDEN, NATIONALITEIT_NIS, STATUS_GSM, STATUS_EMAIL, STATUS_TEL, NUMMER_MUTUALITEIT, NUMMER_SOCIALE_ZEKERHEID, NAAM_TITULARIS, RESERVE, GSM, EMAIL_ADRES, TEKST_CHAR50, GELDIGHEIDSDATUM_DOCUMENT, TIME_STAMP, ERROR_EMAIL, VOORNAAM, ACHTERNAAM, CODE_LAND_GRENSARBEIDERS, DATUM_EMAIL)
VALUES(1, 'UPDFZZ02', 1140217, 0, '150', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '064285296', ' ', ' ', 0, '2014-11-15 22:41:34.941', ' ', 'NICOLAS', 'RECCHIA', ' ', 0);
